import { Subject, Chapter } from './types';

export const NEET_SYLLABUS: Chapter[] = [
  // Physics
  { id: 'phy_1', name: 'Units and Measurements', subject: Subject.PHYSICS },
  { id: 'phy_2', name: 'Motion in a Straight Line', subject: Subject.PHYSICS },
  { id: 'phy_3', name: 'Motion in a Plane', subject: Subject.PHYSICS },
  { id: 'phy_4', name: 'Laws of Motion', subject: Subject.PHYSICS },
  { id: 'phy_5', name: 'Work, Energy and Power', subject: Subject.PHYSICS },
  { id: 'phy_6', name: 'System of Particles and Rotational Motion', subject: Subject.PHYSICS },
  { id: 'phy_7', name: 'Gravitation', subject: Subject.PHYSICS },
  { id: 'phy_8', name: 'Mechanical Properties of Solids', subject: Subject.PHYSICS },
  { id: 'phy_9', name: 'Mechanical Properties of Fluids', subject: Subject.PHYSICS },
  { id: 'phy_10', name: 'Thermal Properties of Matter', subject: Subject.PHYSICS },
  { id: 'phy_11', name: 'Thermodynamics', subject: Subject.PHYSICS },
  { id: 'phy_12', name: 'Kinetic Theory', subject: Subject.PHYSICS },
  { id: 'phy_13', name: 'Oscillations', subject: Subject.PHYSICS },
  { id: 'phy_14', name: 'Waves', subject: Subject.PHYSICS },
  { id: 'phy_15', name: 'Electric Charges and Fields', subject: Subject.PHYSICS },
  { id: 'phy_16', name: 'Electrostatic Potential and Capacitance', subject: Subject.PHYSICS },
  { id: 'phy_17', name: 'Current Electricity', subject: Subject.PHYSICS },
  { id: 'phy_18', name: 'Moving Charges and Magnetism', subject: Subject.PHYSICS },
  { id: 'phy_19', name: 'Magnetism and Matter', subject: Subject.PHYSICS },
  { id: 'phy_20', name: 'Electromagnetic Induction', subject: Subject.PHYSICS },
  { id: 'phy_21', name: 'Alternating Current', subject: Subject.PHYSICS },
  { id: 'phy_22', name: 'Electromagnetic Waves', subject: Subject.PHYSICS },
  { id: 'phy_23', name: 'Ray Optics and Optical Instruments', subject: Subject.PHYSICS },
  { id: 'phy_24', name: 'Wave Optics', subject: Subject.PHYSICS },
  { id: 'phy_25', name: 'Dual Nature of Radiation and Matter', subject: Subject.PHYSICS },
  { id: 'phy_26', name: 'Atoms', subject: Subject.PHYSICS },
  { id: 'phy_27', name: 'Nuclei', subject: Subject.PHYSICS },
  { id: 'phy_28', name: 'Semiconductor Electronics', subject: Subject.PHYSICS },

  // Chemistry
  { id: 'chem_1', name: 'Some Basic Concepts of Chemistry', subject: Subject.CHEMISTRY },
  { id: 'chem_2', name: 'Structure of Atom', subject: Subject.CHEMISTRY },
  { id: 'chem_3', name: 'Classification of Elements and Periodicity', subject: Subject.CHEMISTRY },
  { id: 'chem_4', name: 'Chemical Bonding and Molecular Structure', subject: Subject.CHEMISTRY },
  { id: 'chem_5', name: 'Chemical Thermodynamics', subject: Subject.CHEMISTRY },
  { id: 'chem_6', name: 'Equilibrium', subject: Subject.CHEMISTRY },
  { id: 'chem_7', name: 'Redox Reactions', subject: Subject.CHEMISTRY },
  { id: 'chem_8', name: 'p-Block Elements (Group 13-18)', subject: Subject.CHEMISTRY },
  { id: 'chem_9', name: 'Organic Chemistry - Basic Principles', subject: Subject.CHEMISTRY },
  { id: 'chem_10', name: 'Hydrocarbons', subject: Subject.CHEMISTRY },
  { id: 'chem_11', name: 'Solutions', subject: Subject.CHEMISTRY },
  { id: 'chem_12', name: 'Electrochemistry', subject: Subject.CHEMISTRY },
  { id: 'chem_13', name: 'Chemical Kinetics', subject: Subject.CHEMISTRY },
  { id: 'chem_14', name: 'd-and f-Block Elements', subject: Subject.CHEMISTRY },
  { id: 'chem_15', name: 'Coordination Compounds', subject: Subject.CHEMISTRY },
  { id: 'chem_16', name: 'Haloalkanes and Haloarenes', subject: Subject.CHEMISTRY },
  { id: 'chem_17', name: 'Alcohols, Phenols and Ethers', subject: Subject.CHEMISTRY },
  { id: 'chem_18', name: 'Aldehydes, Ketones and Carboxylic Acids', subject: Subject.CHEMISTRY },
  { id: 'chem_19', name: 'Amines', subject: Subject.CHEMISTRY },
  { id: 'chem_20', name: 'Biomolecules', subject: Subject.CHEMISTRY },

  // Botany
  { id: 'bot_1', name: 'The Living World', subject: Subject.BOTANY },
  { id: 'bot_2', name: 'Biological Classification', subject: Subject.BOTANY },
  { id: 'bot_3', name: 'Plant Kingdom', subject: Subject.BOTANY },
  { id: 'bot_4', name: 'Morphology of Flowering Plants', subject: Subject.BOTANY },
  { id: 'bot_5', name: 'Anatomy of Flowering Plants', subject: Subject.BOTANY },
  { id: 'bot_6', name: 'Cell: The Unit of Life', subject: Subject.BOTANY },
  { id: 'bot_7', name: 'Biomolecules (Botany Context)', subject: Subject.BOTANY },
  { id: 'bot_8', name: 'Cell Cycle and Cell Division', subject: Subject.BOTANY },
  { id: 'bot_9', name: 'Photosynthesis in Higher Plants', subject: Subject.BOTANY },
  { id: 'bot_10', name: 'Respiration in Plants', subject: Subject.BOTANY },
  { id: 'bot_11', name: 'Plant Growth and Development', subject: Subject.BOTANY },
  { id: 'bot_12', name: 'Sexual Reproduction in Flowering Plants', subject: Subject.BOTANY },
  { id: 'bot_13', name: 'Principles of Inheritance and Variation', subject: Subject.BOTANY },
  { id: 'bot_14', name: 'Molecular Basis of Inheritance', subject: Subject.BOTANY },
  { id: 'bot_15', name: 'Organisms and Populations', subject: Subject.BOTANY },
  { id: 'bot_16', name: 'Ecosystem', subject: Subject.BOTANY },
  { id: 'bot_17', name: 'Biodiversity and Conservation', subject: Subject.BOTANY },

  // Zoology
  { id: 'zoo_1', name: 'Animal Kingdom', subject: Subject.ZOOLOGY },
  { id: 'zoo_2', name: 'Structural Organisation in Animals', subject: Subject.ZOOLOGY },
  { id: 'zoo_3', name: 'Breathing and Exchange of Gases', subject: Subject.ZOOLOGY },
  { id: 'zoo_4', name: 'Body Fluids and Circulation', subject: Subject.ZOOLOGY },
  { id: 'zoo_5', name: 'Excretory Products and their Elimination', subject: Subject.ZOOLOGY },
  { id: 'zoo_6', name: 'Locomotion and Movement', subject: Subject.ZOOLOGY },
  { id: 'zoo_7', name: 'Neural Control and Coordination', subject: Subject.ZOOLOGY },
  { id: 'zoo_8', name: 'Chemical Coordination and Integration', subject: Subject.ZOOLOGY },
  { id: 'zoo_9', name: 'Human Reproduction', subject: Subject.ZOOLOGY },
  { id: 'zoo_10', name: 'Reproductive Health', subject: Subject.ZOOLOGY },
  { id: 'zoo_11', name: 'Evolution', subject: Subject.ZOOLOGY },
  { id: 'zoo_12', name: 'Human Health and Disease', subject: Subject.ZOOLOGY },
  { id: 'zoo_13', name: 'Biotechnology: Principles and Processes', subject: Subject.ZOOLOGY },
  { id: 'zoo_14', name: 'Biotechnology and its Applications', subject: Subject.ZOOLOGY },
];